{
 "title": "Dashboard de Rede Sanitizado",
 "description": "Dashboard Monitoramento Firewall Fortigate ",
 "tags": [
  "fortigete",
  "firewall"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "IP_ADDRESS", "label": "IP do Dispositivo" },
   { "name": "VLAN_ID", "label": "ID da VLAN" }
  ]
 },
 "panels": [
  {
   "title": "Informações do firewall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "Firewall",
   "targets": [
    {}
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/Informacoes do firewall/" },
     "evaltype": "0",
     "group": { "filter": "Rede Núcleo - ${IP_ADDRESS}" },
     "host": {
      "filter": "Firewall Corporativo - ${IP_ADDRESS}"
     },
     "item": { "filter": "Hard Disk Capacity" },
     "itemTag": { "filter": "Application: Storage" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "/Informacoes do firewall/" },
     "evaltype": "0",
     "group": { "filter": "Rede Núcleo - ${IP_ADDRESS}" },
     "host": {
      "filter": "Firewall Corporativo - ${IP_ADDRESS}"
     },
     "item": { "filter": "Hard Disk Usage" },
     "itemTag": { "filter": "Application: Storage" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "/Informacoes do firewall/" },
     "evaltype": "0",
     "group": { "filter": "Rede Núcleo - ${IP_ADDRESS}" },
     "host": {
      "filter": "Firewall Corporativo - ${IP_ADDRESS}"
     },
     "item": { "filter": "Hard Disk Usage Rate" },
     "itemTag": { "filter": "Application: Storage" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Memory usage in %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/Informacoes do firewall/" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/(.*)/",
        "Memory usage"
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      }
     ],
     "group": { "filter": "Rede Núcleo - ${IP_ADDRESS}" },
     "host": {
      "filter": "Firewall Corporativo - ${IP_ADDRESS}"
     },
     "item": { "filter": "Memory usage" },
     "itemTag": { "filter": "Application: Memory" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "CPU usage in %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/Informacoes do firewall/" },
     "evaltype": "0",
     "group": { "filter": "Rede Núcleo - ${IP_ADDRESS}" },
     "host": {
      "filter": "Firewall Corporativo - ${IP_ADDRESS}"
     },
     "item": { "filter": "CPU usage" },
     "itemTag": { "filter": "Application: CPU" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Interfaces network traffic information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "LAG SW CORE",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": {
      "filter": "/Informacoes de trafego de rede da/"
     },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/(.*)/",
        "Bits received"
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      }
     ],
     "group": { "filter": "Rede Núcleo - ${IP_ADDRESS}" },
     "host": {
      "filter": "Firewall Corporativo - ${IP_ADDRESS}"
     },
     "item": {
      "filter": "Interface LAG_SW_CORE(): Bits received"
     },
     "itemTag": {
      "filter": "Application: Interface LAG_SW_CORE()"
     },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "/Informacoes de trafego de rede da/"
     },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/(.*)/",
        "Bits sent"
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      }
     ],
     "group": { "filter": "Rede Núcleo - ${IP_ADDRESS}" },
     "host": {
      "filter": "Firewall Corporativo - ${IP_ADDRESS}"
     },
     "item": {
      "filter": "Interface LAG_SW_CORE(): Bits sent"
     },
     "itemTag": {
      "filter": "Application: Interface LAG_SW_CORE()"
     },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "VLAN_${VLAN_ID} PROVEDOR_LINK",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": {
      "filter": "/Informacoes de trafego de rede da/"
     },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/(.*)/",
        "Bits received"
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      }
     ],
     "group": { "filter": "Rede Núcleo - ${IP_ADDRESS}" },
     "host": {
      "filter": "Firewall Corporativo - ${IP_ADDRESS}"
     },
     "item": {
      "filter": "Interface VLAN_${VLAN_ID}(VLAN_PROVEDOR_LINK): Bits received"
     },
     "itemTag": {
      "filter": "Application: Interface VLAN_${VLAN_ID}(VLAN_PROVEDOR_LINK)"
     },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "/Informacoes de trafego de rede da/"
     },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/(.*)/",
        "Bits sent"
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      }
     ],
     "group": { "filter": "Rede Núcleo - ${IP_ADDRESS}" },
     "host": {
      "filter": "Firewall Corporativo - ${IP_ADDRESS}"
     },
     "item": {
      "filter": "Interface VLAN_${VLAN_ID}(VLAN_PROVEDOR_LINK): Bits sent"
     },
     "itemTag": {
      "filter": "Application: Interface VLAN_${VLAN_ID}(VLAN_PROVEDOR_LINK)"
     },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "VLAN_1200 PROVEDOR_LINK",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": {
      "filter": "/Informacoes de trafego de rede da/"
     },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/(.*)/",
        "Bits received"
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      }
     ],
     "group": { "filter": "Rede Núcleo - ${IP_ADDRESS}" },
     "host": {
      "filter": "Firewall Corporativo - ${IP_ADDRESS}"
     },
     "item": {
      "filter": "Interface VLAN_1200(VLAN_PROVEDOR_LINK): Bits received"
     },
     "itemTag": {
      "filter": "Application: Interface VLAN_1200(VLAN_PROVEDOR_LINK)"
     },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": {
      "filter": "/Informacoes de trafego de rede da/"
     },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/(.*)/",
        "Bits sent"
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      }
     ],
     "group": { "filter": "Rede Núcleo - ${IP_ADDRESS}" },
     "host": {
      "filter": "Firewall Corporativo - ${IP_ADDRESS}"
     },
     "item": {
      "filter": "Interface VLAN_1200(VLAN_PROVEDOR_LINK): Bits sent"
     },
     "itemTag": {
      "filter": "Application: Interface VLAN_1200(VLAN_PROVEDOR_LINK)"
     },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "FortiGate Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": {
      "filter": "/Informacoes de monitoramento do link de internet/"
     },
     "evaltype": "0",
     "group": { "filter": "Rede Núcleo - ${IP_ADDRESS}" },
     "host": {
      "filter": "Firewall Corporativo - ${IP_ADDRESS}"
     },
     "item": { "filter": "FortiGate Uptime" },
     "itemTag": { "filter": "Application: Status" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Informações de Proteção ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": " Informações de IPS ",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/Informacoes do firewall/" },
     "evaltype": "0",
     "group": { "filter": "Rede Núcleo - ${IP_ADDRESS}" },
     "host": {
      "filter": "Firewall Corporativo - ${IP_ADDRESS}"
     },
     "item": { "filter": "Intrusions detected - Critical" },
     "itemTag": { "filter": "Application: IPS" },
     "macro": { "filter": "" },
     "mode": 2,
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "/Informacoes do firewall/" },
     "evaltype": "0",
     "group": { "filter": "Rede Núcleo - ${IP_ADDRESS}" },
     "host": {
      "filter": "Firewall Corporativo - ${IP_ADDRESS}"
     },
     "item": { "filter": "Intrusions detected - High" },
     "itemTag": { "filter": "Application: IPS" },
     "macro": { "filter": "" },
     "mode": 2,
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "/Informacoes do firewall/" },
     "evaltype": "0",
     "group": { "filter": "Rede Núcleo - ${IP_ADDRESS}" },
     "host": {
      "filter": "Firewall Corporativo - ${IP_ADDRESS}"
     },
     "item": {
      "filter": "Intrusions detected - Anomaly based"
     },
     "itemTag": { "filter": "Application: IPS" },
     "macro": { "filter": "" },
     "mode": 2,
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "/Informacoes do firewall/" },
     "evaltype": "0",
     "group": { "filter": "Rede Núcleo - ${IP_ADDRESS}" },
     "host": {
      "filter": "Firewall Corporativo - ${IP_ADDRESS}"
     },
     "item": { "filter": "Intrusions detected" },
     "itemTag": { "filter": "Application: IPS" },
     "macro": { "filter": "" },
     "mode": 2,
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "/Informacoes do firewall/" },
     "evaltype": "0",
     "group": { "filter": "Rede Núcleo - ${IP_ADDRESS}" },
     "host": {
      "filter": "Firewall Corporativo - ${IP_ADDRESS}"
     },
     "item": { "filter": "Intrusions detected - Info" },
     "itemTag": { "filter": "Application: IPS" },
     "macro": { "filter": "" },
     "mode": 2,
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "/Informacoes do firewall/" },
     "evaltype": "0",
     "group": { "filter": "Rede Núcleo - ${IP_ADDRESS}" },
     "host": {
      "filter": "Firewall Corporativo - ${IP_ADDRESS}"
     },
     "item": { "filter": "Intrusions detected - Low" },
     "itemTag": { "filter": "Application: IPS" },
     "macro": { "filter": "" },
     "mode": 2,
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "/Informacoes do firewall/" },
     "evaltype": "0",
     "group": { "filter": "Rede Núcleo - ${IP_ADDRESS}" },
     "host": {
      "filter": "Firewall Corporativo - ${IP_ADDRESS}"
     },
     "item": { "filter": "Intrusions detected - Medium" },
     "itemTag": { "filter": "Application: IPS" },
     "macro": { "filter": "" },
     "mode": 2,
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "/Informacoes do firewall/" },
     "evaltype": "0",
     "group": { "filter": "Rede Núcleo - ${IP_ADDRESS}" },
     "host": {
      "filter": "Firewall Corporativo - ${IP_ADDRESS}"
     },
     "item": {
      "filter": "Intrusions detected - Signature based"
     },
     "itemTag": { "filter": "Application: IPS" },
     "macro": { "filter": "" },
     "mode": 2,
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "/Informacoes do firewall/" },
     "evaltype": "0",
     "group": { "filter": "Rede Núcleo - ${IP_ADDRESS}" },
     "host": {
      "filter": "Firewall Corporativo - ${IP_ADDRESS}"
     },
     "item": { "filter": "Intrusions detected - Critical" },
     "itemTag": { "filter": "Application: IPS" },
     "macro": { "filter": "" },
     "mode": 2,
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "/Informacoes do firewall/" },
     "evaltype": "0",
     "group": { "filter": "Rede Núcleo - ${IP_ADDRESS}" },
     "host": {
      "filter": "Firewall Corporativo - ${IP_ADDRESS}"
     },
     "item": { "filter": "Intrusions detected - High" },
     "itemTag": { "filter": "Application: IPS" },
     "macro": { "filter": "" },
     "mode": 2,
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "/Informacoes do firewall/" },
     "evaltype": "0",
     "group": { "filter": "Rede Núcleo - ${IP_ADDRESS}" },
     "host": {
      "filter": "Firewall Corporativo - ${IP_ADDRESS}"
     },
     "item": {
      "filter": "Intrusions detected - Anomaly based"
     },
     "itemTag": { "filter": "Application: IPS" },
     "macro": { "filter": "" },
     "mode": 2,
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "/Informacoes do firewall/" },
     "evaltype": "0",
     "group": { "filter": "Rede Núcleo - ${IP_ADDRESS}" },
     "host": {
      "filter": "Firewall Corporativo - ${IP_ADDRESS}"
     },
     "item": { "filter": "Intrusions detected" },
     "itemTag": { "filter": "Application: IPS" },
     "macro": { "filter": "" },
     "mode": 2,
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "/Informacoes do firewall/" },
     "evaltype": "0",
     "group": { "filter": "Rede Núcleo - ${IP_ADDRESS}" },
     "host": {
      "filter": "Firewall Corporativo - ${IP_ADDRESS}"
     },
     "item": { "filter": "Intrusions detected - Info" },
     "itemTag": { "filter": "Application: IPS" },
     "macro": { "filter": "" },
     "mode": 2,
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "/Informacoes do firewall/" },
     "evaltype": "0",
     "group": { "filter": "Rede Núcleo - ${IP_ADDRESS}" },
     "host": {
      "filter": "Firewall Corporativo - ${IP_ADDRESS}"
     },
     "item": { "filter": "Intrusions detected - Low" },
     "itemTag": { "filter": "Application: IPS" },
     "macro": { "filter": "" },
     "mode": 2,
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "/Informacoes do firewall/" },
     "evaltype": "0",
     "group": { "filter": "Rede Núcleo - ${IP_ADDRESS}" },
     "host": {
      "filter": "Firewall Corporativo - ${IP_ADDRESS}"
     },
     "item": { "filter": "Intrusions detected - Medium" },
     "itemTag": { "filter": "Application: IPS" },
     "macro": { "filter": "" },
     "mode": 2,
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "/Informacoes do firewall/" },
     "evaltype": "0",
     "group": { "filter": "Rede Núcleo - ${IP_ADDRESS}" },
     "host": {
      "filter": "Firewall Corporativo - ${IP_ADDRESS}"
     },
     "item": {
      "filter": "Intrusions detected - Signature based"
     },
     "itemTag": { "filter": "Application: IPS" },
     "macro": { "filter": "" },
     "mode": 2,
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  }
 ]
}